name: package_version

on:
    pull_request:
        branches: master
        paths:
            - "src/**"
            - "package-lock.json"

jobs:
    check-tag-available:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Get package version
              id: package_version
              run: echo "::set-output name=value::$(node -e 'console.log(require("./package.json").version)')"
            - name: Find tag for package version
              id: package_version_exists
              run: echo "::set-output name=value::$(git tag -l "${{ steps.package_version.outputs.value }}")"
            - name: Fail if tag already exists
              if: ${{ steps.package_version_exists.outputs.value }}
              run: |
                  echo "A tag for package version ${{ steps.package_version.outputs.value }} already exists."
                  exit 1

    publish-dryrun-npm:
        runs-on: ubuntu-latest
        needs: [check-tag-available]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run package
            - run: npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-dryrun-gpr:
        runs-on: ubuntu-latest
        needs: [check-tag-available]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com
                  scope: "@johnyherangi"
            - run: npm ci
            - run: npm run package
            - run: echo "registry=https://npm.pkg.github.com/@johnyherangi" >> .npmrc
            - run: npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
